version: '3.2'

services:
  app:
    image: dockersamples/dotnet-album-viewer
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "80:80"
    environment:
      - "Data:Provider=MySQL"
      - "Data:ConnectionString=Server=album-db;Port=3306;Database=AlbumViewer;User=root;SslMode=None"
