apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: album-viewer-ingress
  annotations:
    # Usar regex para manejar rutas específicas
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: albumviewer.local
      http:
        paths:
          # Primero: archivos estáticos (extensiones específicas)
          - path: /.*\.(js|css|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|map)$
            pathType: ImplementationSpecific
            backend:
              service:
                name: album-viewer-service
                port:
                  number: 80
          # Segundo: todas las demás rutas van al index.html
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: album-viewer-service
                port:
                  number: 80