apiVersion: v1
kind: Service
metadata:
  name: album-viewer-service
spec:
  selector:
    app: albumviewer
  ports:
    - protocol: TCP
      port: 80        # Expuesto en el cluster
      targetPort: 80  # Puerto interno del contenedor