apiVersion: v1
kind: Service
metadata:
  name: albumviewer-service
spec:
  selector:
    app: albumviewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # o el puerto en que corre tu app .NET Core dentro del contenedor
