apiVersion: apps/v1
kind: Deployment
metadata:
  name: album-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: album-db
  template:
    metadata:
      labels:
        app: album-db
    spec:
      containers:
        - name: album-db
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: AlbumViewer
---
apiVersion: v1
kind: Service
metadata:
  name: album-db
spec:
  selector:
    app: album-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
