apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: album-viewer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /album-viewer
            pathType: Prefix
            backend:
              service:
                name: album-viewer-service
                port:
                  number: 80
